routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryDetailController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\RegencyController;
use App\Http\Controllers\BoxResourceController;
use App\Http\Controllers\PurchasePriceController;
use App\Http\Controllers\TransportIntensityController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\PapermillCategoryController;
use App\Http\Controllers\PapermillController;

use App\Http\Controllers\Dashboard1Controller;
use App\Http\Controllers\DashboardComparisonController;
use App\Http\Controllers\DashboardTargetController;
use App\Http\Controllers\DashboardShipmentController;
use App\Http\Controllers\DashboardActivitiesController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\ActivityProgramController;
use App\Http\Controllers\ActivityController;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\ParticipantListController;
use App\Http\Controllers\PotentialController;

use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'showFormLogin']);
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [HomeController::class, 'index']);
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});
Route::get('/home', [HomeController::class, 'index']);
Route::resource('categories', CategoryController::class);
Route::resource('categoryDetails', CategoryDetailController::class);
Route::resource('areas', AreaController::class);
Route::post('importArea',[AreaController::class, 'importArea'])->name('areas.importArea');
Route::resource('districts', DistrictController::class);
Route::post('importDistrict',[DistrictController::class, 'importDistrict'])->name('districts.importDistrict');
Route::resource('regencies', RegencyController::class);
Route::post('importRegency',[RegencyController::class, 'importRegency'])->name('regencies.importRegency');
Route::resource('boxResources', BoxResourceController::class);
Route::resource('purchasePrices', PurchasePriceController::class);
Route::resource('transportIntensities', TransportIntensityController::class);
Route::resource('paymentMethods', PaymentMethodController::class);
Route::resource('banks', BankController::class);
Route::resource('papermillCategories', PapermillCategoryController::class);
Route::resource('papermills', PapermillController::class);
Route::get('createPapermill',[PapermillController::class, 'createPapermill'])->name('papermills.createPapermill');

Route::resource('participants', ParticipantController::class);
Route::get('createParticipant',[ParticipantController::class, 'createParticipant'])->name('participants.createParticipant');
Route::post('importParticipant',[ParticipantController::class, 'importParticipant'])->name('participants.importParticipant');
Route::get('getDatatableCollection',[ParticipantController::class, 'getDatatableCollection'])->name('participants.getDatatableCollection');
Route::get('getLineChartDataCollection', [ParticipantController::class, 'getLineChartDataCollection']);
Route::get('getLineChartDataCollection', [ParticipantController::class, 'getLineChartDataCollection']);
Route::get('downloadParticipants', [ParticipantController::class, 'downloadParticipants']);

Route::resource('user-management', UserManagementController::class);
Route::resource('collections', CollectionController::class);
Route::post('importCollection',[CollectionController::class, 'importCollection'])->name('collections.importCollection');
Route::get('downloadCollections', [CollectionController::class, 'downloadCollections']);

Route::resource('sales', SaleController::class);
Route::get('downloadSales', [SaleController::class, 'downloadSales']);
Route::resource('activityPrograms', ActivityProgramController::class);
Route::resource('activities', ActivityController::class);
Route::post('importActivity',[ActivityController::class, 'importActivity'])->name('activities.importActivity');
Route::get('downloadActivities', [ActivityController::class, 'downloadActivities']);

Route::resource('potentials', PotentialController::class);


Route::resource('dashboard1', Dashboard1Controller::class);
Route::get('getNumberOfParticipants', [Dashboard1Controller::class, 'getNumberOfParticipants']);
Route::get('getContribution', [Dashboard1Controller::class, 'getContribution']);
Route::get('getBarContribution', [Dashboard1Controller::class, 'getBarContribution']);
Route::get('getCollectionByFilters', [Dashboard1Controller::class, 'getCollectionByFilters']);
Route::get('getCollection', [Dashboard1Controller::class, 'getCollection']);
Route::get('getLineChartData', [Dashboard1Controller::class, 'getLineChartData']);
Route::get('getMapByFilters', [Dashboard1Controller::class, 'getMapByFilters']);

Route::resource('dashboard-comparison', DashboardComparisonController::class);
Route::get('getComparisonLineChartData', [DashboardComparisonController::class, 'getComparisonLineChartData']);

Route::resource('dashboard-target', DashboardTargetController::class);
Route::get('getActualTargetBar', [DashboardTargetController::class, 'getActualTargetBar']);
Route::get('getActualTargetBarByMonth', [DashboardTargetController::class, 'getActualTargetBarByMonth']);
Route::get('getTargetPapermillDonut', [DashboardTargetController::class, 'getTargetPapermillDonut']);

Route::resource('map', MapController::class);
Route::get('getMapParticipantsInformation', [MapController::class, 'getMapParticipantsInformation']);

Route::resource('dashboard-shipment', DashboardShipmentController::class);
Route::get('getSales', [DashboardShipmentController::class, 'getSales']);
Route::get('getSentVsReceivedCustom', [DashboardShipmentController::class, 'getSentVsReceivedCustom']);
Route::get('getMCCCustom', [DashboardShipmentController::class, 'getMCCCustom']);

Route::resource('dashboard-activities', DashboardActivitiesController::class);
Route::get('getActivities', [DashboardActivitiesController::class, 'getActivities']);


Route::resource('participantList', ParticipantListController::class);
Route::get('downloadParticipantList', [ParticipantListController::class, 'downloadParticipantList']);

app/Models/PaymentMethod.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PaymentMethod extends Model
{
    use HasFactory;

    protected $fillable = ['payment_method','description','created_by','created_datetime','last_modified_by','last_modified_datetime'];
}

app/Http/Controllers/PaymentMethodController.php
<?php

namespace App\Http\Controllers;

use App\Models\PaymentMethod;
use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Facades\Auth;


class PaymentMethodController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();

        $paymentMethods = PaymentMethod::latest()->get();
        
        if ($request->ajax()) {
            $data = PaymentMethod::latest()->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
   
                           $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editPaymentMethod">Edit</a>';
   
                           $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deletePaymentMethod">Delete</a>';
    
                            return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('paymentMethod/index',compact('paymentMethods','user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        PaymentMethod::updateOrCreate(
            ['id' => $request->paymentMethod_id],
            [
                'payment_method' => $request->payment_method, 
                'description' => $request->description,
                'created_by' => $request->created_by,
                'created_datetime' => $request->created_datetime,
                'last_modified_by' => $request->last_modified_by,
                'last_modified_datetime' => $request->last_modified_datetime,
            ]
        );        
   
        return response()->json(['success'=>'Payment Method saved successfully.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function show(PaymentMethod $paymentMethod)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $paymentMethod = PaymentMethod::find($id);
        return response()->json($paymentMethod);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PaymentMethod $paymentMethod)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PaymentMethod::find($id)->delete();
     
        return response()->json(['success'=>'Payment Method deleted successfully.']);
    }
}

resources/views/paymentMethod/index.blade.php
@extends('template', ['user'=>$user])
@section('paymentMethods','active')
@push('css_extend')
<style type="text/css">
    label.error {
        color: red !important;
        text-transform: none !important;
        font-weight: normal !important;
    }
</style>
@endpush
@section('content')
        <!-- BEGIN: Content-->
        <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row mb-1">
                <div class="content-header-left col-md-12 col-12 mb-2 breadcrumb-new">
                    <h3 class="content-header-title mb-0 d-inline-block">Payment Method</h3>
                    <div class="row breadcrumbs-top d-inline-block">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{url('paymentMethods')}}">Home</a>
                                </li>
                                <li class="breadcrumb-item">Master Data</a>
                                </li>
                                <li class="breadcrumb-item active">Payment Method
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Zero configuration table -->
                <section id="configuration">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header pb-0">
                                    <h4 class="card-title">Payment Method Data Master</h4>
                                    <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                                    <button type="button" class="btn btn-success btn-min-width mr-1 mb-1" href="javascript:void(0)" id="createNewPaymentMethod">Add New Payment Method</button>

                                        @include('paymentMethod.modal')
                                        <div class="table-responsive">
                                            <table id="paymentMethodTable" class="table table-striped table-bordered zero-configuration">
                                                <thead>
                                                    <tr>
                                                        <th width="30px">No</th>
                                                        <th>Payment Method</th>
                                                        <th>Description</th>
                                                        <th width="250px">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th width="30px">No</th>
                                                        <th>Payment Method</th>
                                                        <th>Description</th>
                                                        <th width="250px">Action</th>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!--/ Zero configuration table -->
            </div>
        </div>
    </div>
        <!-- END: Content -->
        @endsection

@push('ajax_crud')
<script type="text/javascript">
$(document).ready(function(e) {
    var form = $("#paymentMethodForm");
    form.validate();
});
  $(function () {
    var validator = $("#paymentMethodForm").validate();
    $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
      });

      var table = $('#paymentMethodTable').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('paymentMethods.index') }}",
          columns: [
              {data: null},
              {data: 'payment_method', name: 'payment_method'},
              {data: 'description', name: 'description'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      table.on('draw.dt', function () {
            var info = table.page.info();
            table.column(0, { search: 'applied', order: 'applied', page: 'applied' }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

      $('#createNewPaymentMethod').click(function () {
          validator.resetForm();
          $('#saveBtn').val("create");
          $('#paymentMethod_id').val('');
          $('#paymentMethodForm').trigger("reset");
          $('#modalHeading').html("Create New Payment Method");
          $('#paymentMethodModal').modal('show');
      });

      $('body').on('click', '.editPaymentMethod', function () {
        validator.resetForm();
        var paymentMethod_id = $(this).data('id');
        $.get("{{ route('paymentMethods.index') }}" +'/' + paymentMethod_id +'/edit', function (data) {
            $('#modalHeading').html("Edit Payment Method");
            $('#saveBtn').val("edit");
            $('#paymentMethodModal').modal('show');
            $('#paymentMethod_id').val(data.id);
            $('#payment_method').val(data.payment_method);
            $('#description').val(data.description);
            $('#created_by').val(data.created_by);
            $('#created_datetime').val(data.created_datetime);
            $('#last_modified_by').val(data.last_modified_by);
            $('#last_modified_datetime').val(data.last_modified_datetime);
        })
     });

      $('#saveBtn').click(function (e) {
        if ($('#paymentMethodForm').valid()) {
            e.preventDefault();
            if ($('#saveBtn').val() == "create")  {
                $('#created_by').val("Deva Dwi A");
                $('#created_datetime').val(new Date().toISOString().slice(0, 19).replace('T', ' '));
                $('#last_modified_by').val(null);
                $('#last_modified_datetime').val(null);
                var alertMessage = 'Payment Method berhasil ditambahkan.';
            } else {
                $('#created_by').val("Deva Dwi A");
                $('#created_datetime').val(new Date().toISOString().slice(0, 19).replace('T', ' '));
                $('#last_modified_by').val("Deva Dwi A Edit");
                $('#last_modified_datetime').val(new Date().toISOString().slice(0, 19).replace('T', ' '));
                var alertMessage = 'Payment Method berhasil di edit.';
            }
            $(this).html('Save');

            $.ajax({
                data: $('#paymentMethodForm').serialize(),
                url: "{{ route('paymentMethods.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {

                    $('#paymentMethodForm').trigger("reset");
                    $('#paymentMethodModal').modal('hide');
                    table.draw();
                    toastr.options = {
                        "positionClass": "toast-bottom-right"
                    };
                    toastr.success(alertMessage);

                },
                error: function (data) {
                    console.log('Error:', data);
                    toastr.error('Gagal menambahkan data.');
                    $('#saveBtn').html('Save Changes');
                }
            });
        }

      });

      $('body').on('click', '.deletePaymentMethod', function () {

          var paymentMethod_id = $(this).data("id");
          swal({
            title: "Are you sure?",
            text: "Apakah anda yakin untuk menghapus data ini ?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: "DELETE",
                        url: "{{ route('paymentMethods.store') }}"+'/'+paymentMethod_id,
                        success: function (data) {
                            toastr.options = {
                                "positionClass": "toast-bottom-right"
                            }
                            toastr.success('Payment Method berhasil dihapus.');
                            table.draw();
                        },
                        error: function (data) {
                            console.log('Error:', data);
                        }
                    });
                } else {}
            });

      });

    });
</script>

@endpush

resources/views/paymentMethod/modal.blade.php
<div class="modal fade text-left" id="paymentMethodModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="paymentMethodForm" name="paymentMethodForm" class="form-horizontal">
                    <input type="hidden" id="paymentMethod_id" name="paymentMethod_id" value="">
                    <input type="hidden" id="created_by" name="created_by" value="">
                    <input type="hidden" id="created_datetime" name="created_datetime" value="">
                    <input type="hidden" id="last_modified_by" name="last_modified_by" value="">
                    <input type="hidden" id="last_modified_datetime" name="last_modified_datetime" value="">
                    <div class="form-group">
                        <label for="name" class="control-label">Payment Method</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="payment_method" name="payment_method" placeholder="Enter Payment Method" value="" maxlength="50" required="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Description</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="description" name="description" placeholder="Enter Description" value="" maxlength="50">
                        </div>
                    </div>
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" value="" class="btn btn-primary" id="saveBtn" value="create">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>