routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoryDetailController;
use App\Http\Controllers\AreaController;
use App\Http\Controllers\DistrictController;
use App\Http\Controllers\RegencyController;
use App\Http\Controllers\BoxResourceController;
use App\Http\Controllers\PurchasePriceController;
use App\Http\Controllers\TransportIntensityController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\CollectionController;
use App\Http\Controllers\PapermillCategoryController;
use App\Http\Controllers\PapermillController;

use App\Http\Controllers\Dashboard1Controller;
use App\Http\Controllers\DashboardComparisonController;
use App\Http\Controllers\DashboardTargetController;
use App\Http\Controllers\DashboardShipmentController;
use App\Http\Controllers\DashboardActivitiesController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\ActivityProgramController;
use App\Http\Controllers\ActivityController;

use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\ParticipantListController;
use App\Http\Controllers\PotentialController;

use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthController::class, 'showFormLogin']);
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', [HomeController::class, 'index']);
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');

});
Route::get('/home', [HomeController::class, 'index']);
Route::resource('categories', CategoryController::class);
Route::resource('categoryDetails', CategoryDetailController::class);
Route::resource('areas', AreaController::class);
Route::post('importArea',[AreaController::class, 'importArea'])->name('areas.importArea');
Route::resource('districts', DistrictController::class);
Route::post('importDistrict',[DistrictController::class, 'importDistrict'])->name('districts.importDistrict');
Route::resource('regencies', RegencyController::class);
Route::post('importRegency',[RegencyController::class, 'importRegency'])->name('regencies.importRegency');
Route::resource('boxResources', BoxResourceController::class);
Route::resource('purchasePrices', PurchasePriceController::class);
Route::resource('transportIntensities', TransportIntensityController::class);
Route::resource('paymentMethods', PaymentMethodController::class);
Route::resource('banks', BankController::class);
Route::resource('papermillCategories', PapermillCategoryController::class);
Route::resource('papermills', PapermillController::class);
Route::get('createPapermill',[PapermillController::class, 'createPapermill'])->name('papermills.createPapermill');

Route::resource('participants', ParticipantController::class);
Route::get('createParticipant',[ParticipantController::class, 'createParticipant'])->name('participants.createParticipant');
Route::post('importParticipant',[ParticipantController::class, 'importParticipant'])->name('participants.importParticipant');
Route::get('getDatatableCollection',[ParticipantController::class, 'getDatatableCollection'])->name('participants.getDatatableCollection');
Route::get('getLineChartDataCollection', [ParticipantController::class, 'getLineChartDataCollection']);
Route::get('getLineChartDataCollection', [ParticipantController::class, 'getLineChartDataCollection']);
Route::get('downloadParticipants', [ParticipantController::class, 'downloadParticipants']);

Route::resource('user-management', UserManagementController::class);
Route::resource('collections', CollectionController::class);
Route::post('importCollection',[CollectionController::class, 'importCollection'])->name('collections.importCollection');
Route::get('downloadCollections', [CollectionController::class, 'downloadCollections']);

Route::resource('sales', SaleController::class);
Route::get('downloadSales', [SaleController::class, 'downloadSales']);
Route::resource('activityPrograms', ActivityProgramController::class);
Route::resource('activities', ActivityController::class);
Route::post('importActivity',[ActivityController::class, 'importActivity'])->name('activities.importActivity');
Route::get('downloadActivities', [ActivityController::class, 'downloadActivities']);

Route::resource('potentials', PotentialController::class);


Route::resource('dashboard1', Dashboard1Controller::class);
Route::get('getNumberOfParticipants', [Dashboard1Controller::class, 'getNumberOfParticipants']);
Route::get('getContribution', [Dashboard1Controller::class, 'getContribution']);
Route::get('getBarContribution', [Dashboard1Controller::class, 'getBarContribution']);
Route::get('getCollectionByFilters', [Dashboard1Controller::class, 'getCollectionByFilters']);
Route::get('getCollection', [Dashboard1Controller::class, 'getCollection']);
Route::get('getLineChartData', [Dashboard1Controller::class, 'getLineChartData']);
Route::get('getMapByFilters', [Dashboard1Controller::class, 'getMapByFilters']);

Route::resource('dashboard-comparison', DashboardComparisonController::class);
Route::get('getComparisonLineChartData', [DashboardComparisonController::class, 'getComparisonLineChartData']);

Route::resource('dashboard-target', DashboardTargetController::class);
Route::get('getActualTargetBar', [DashboardTargetController::class, 'getActualTargetBar']);
Route::get('getActualTargetBarByMonth', [DashboardTargetController::class, 'getActualTargetBarByMonth']);
Route::get('getTargetPapermillDonut', [DashboardTargetController::class, 'getTargetPapermillDonut']);

Route::resource('map', MapController::class);
Route::get('getMapParticipantsInformation', [MapController::class, 'getMapParticipantsInformation']);

Route::resource('dashboard-shipment', DashboardShipmentController::class);
Route::get('getSales', [DashboardShipmentController::class, 'getSales']);
Route::get('getSentVsReceivedCustom', [DashboardShipmentController::class, 'getSentVsReceivedCustom']);
Route::get('getMCCCustom', [DashboardShipmentController::class, 'getMCCCustom']);

Route::resource('dashboard-activities', DashboardActivitiesController::class);
Route::get('getActivities', [DashboardActivitiesController::class, 'getActivities']);


Route::resource('participantList', ParticipantListController::class);
Route::get('downloadParticipantList', [ParticipantListController::class, 'downloadParticipantList']);

app/Models/Papermill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Papermill extends Model
{
    use HasFactory;

    protected $fillable = ['papermill_name','id_papermill_category','contact_name_1','contact_position_1','contact_phone_1','contact_email_1','address','latitude','langitude','id_area','id_district','id_regency','id_purchase_price','id_payment_method','id_bank','bank_branch','bank_account_number','bank_account_holder_name','created_by','created_datetime','last_modified_by','last_modified_datetime'];

}

app/Http/Controllers/PapermillController.php
<?php

namespace App\Http\Controllers;

use App\Models\Papermill;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use DataTables;

class PapermillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = Auth::user();

        $papermills = DB::table('papermills')
            ->leftJoin('papermill_categories', function ($join) {
                $join->on('papermills.id_papermill_category', '=', 'papermill_categories.id');
            })
            ->leftJoin('regencies', function ($join) {
                $join->on('papermills.id_regency', '=', 'regencies.id');
            })
            ->leftJoin('districts', function ($join) {
                $join->on('papermills.id_district', '=', 'districts.id');
            })
            ->select(
                'papermills.id',
                'papermills.papermill_name',
                'papermill_categories.papermill_category_name',
                'districts.district_name',
                'regencies.regency_name',
            )
            ->get();

        if ($request->ajax()) {
            return Datatables::of($papermills)
                ->addIndexColumn()
                ->addColumn('action', function($row){

                    $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editPapermill">Edit</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deletePapermill">Delete</a>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('papermill/index',compact('papermills', 'user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = Papermill::updateOrCreate(
            ['id' => $request->papermill_id],
            [
                'papermill_name' => $request->papermill_name,
                'id_papermill_category' => $request->id_papermill_category,
                'contact_name_1' => $request->contact_name_1,
                'contact_position_1' => $request->contact_position_1,
                'contact_phone_1' => $request->contact_phone_1,
                'contact_email_1' => $request->contact_email_1,

                'address' => $request->address,
                'latitude' => $request->latitude,
                'langitude' => $request->langitude,
                'id_area' => $request->id_area,
                'id_district' => $request->id_district,
                'id_regency' => $request->id_regency,

                'id_purchase_price' => $request->id_purchase_price,

                'id_payment_method' => $request->id_payment_method,
                'id_bank' => $request->id_bank,
                'bank_branch' => $request->bank_branch,
                'bank_account_number' => $request->bank_account_number,
                'bank_account_holder_name' => $request->bank_account_holder_name,

                'created_by' => $request->created_by,
                'created_datetime' => $request->created_datetime,
                'last_modified_by' => $request->last_modified_by,
                'last_modified_datetime' => $request->last_modified_datetime,
            ]
        );

        return response()->json(['success'=>'Papermill saved successfully.','data'=>$data]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Papermill  $papermill
     * @return \Illuminate\Http\Response
     */
    public function show(Papermill $papermill)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Papermill  $papermill
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();

        $papermill = Papermill::find($id);
        $papermill_categories = DB::table('papermill_categories')->get();
        $areas = DB::table('areas')->get();
        $districts = DB::table('districts')->get();
        $regencies = DB::table('regencies')->get();
        $purchase_prices = DB::table('purchase_prices')->get();
        $payment_methods = DB::table('payment_methods')->get();
        $banks = DB::table('banks')->get();

        return view('papermill/edit',
            compact('user','papermill','papermill_categories','areas','districts','regencies','purchase_prices','payment_methods','banks'));
    }

    public function destroy($id)
    {
        Papermill::find($id)->delete();

        return response()->json(['success'=>'Papermill deleted successfully.']);
    }

    public static function createPapermill()
    {
        $user = Auth::user();

        $papermill_categories = DB::table('papermill_categories')->get();
        $areas = DB::table('areas')->get();
        $districts = DB::table('districts')->get();
        $regencies = DB::table('regencies')->get();
        $purchase_prices = DB::table('purchase_prices')->get();
        $payment_methods = DB::table('payment_methods')->get();
        $banks = DB::table('banks')->get();

        return view('papermill/create',
            compact('user','papermill_categories','areas','districts','regencies','purchase_prices','payment_methods','banks'));
    }
}

resources/views/papermill/index.blade.php
@extends('template', ['user'=>$user])

@section('papermills','active')

@section('content')
<?php use App\Http\Controllers\PapermillController;?>
        <!-- BEGIN: Content-->
        <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row mb-1">
                <div class="content-header-left col-md-12 col-12 mb-2 breadcrumb-new">
                    <h3 class="content-header-title mb-0 d-inline-block">Papermill</h3>
                    <div class="row breadcrumbs-top d-inline-block">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{url('papermills')}}">Home</a>
                                </li>
                                <li class="breadcrumb-item">Master Data</a>
                                </li>
                                <li class="breadcrumb-item active">Papermill
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Zero configuration table -->
                <section id="configuration">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header pb-0">
                                    <h4 class="card-title">Papermill Data Master</h4>
                                    <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                                    <div class="heading-elements">
                                        <ul class="list-inline mb-0">
                                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="card-content collapse show">
                                    <div class="card-body card-dashboard">
                                        <button type="button" class="btn btn-success btn-min-width mr-1 mb-1" href="javascript:void(0)" id="createNewPapermill">Add New Papermill</button>
                                        <div class="table-responsive">
                                            <table id="papermillTable" class="table table-striped table-bordered zero-configuration" width="100%">
                                                <thead>
                                                    <tr>
                                                        <th width="30px">No</th>
                                                        <th>Papermill Name</th>
                                                        <th>Category</th>
                                                        <th>District</th>
                                                        <th>Regency</th>
                                                        <th width="250px">Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>

                                                </tbody>
                                                <tfoot>
                                                    <tr>
                                                        <th width="30px">No</th>
                                                        <th>Papermill Name</th>
                                                        <th>Category</th>
                                                        <th>District</th>
                                                        <th>Regency</th>
                                                        <th width="250px">Action</th>
                                                    </tr>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!--/ Zero configuration table -->
            </div>
        </div>
    </div>
        <!-- END: Content -->
        @endsection

@push('ajax_crud')
<script type="text/javascript">
  $(function () {

    $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
      });

      var table = $('#papermillTable').DataTable({
          processing: true,
          serverSide: true,
          ajax: "{{ route('papermills.index') }}",
          columns: [
              {data: null},
              {data: 'papermill_name', name: 'papermill_name'},
              {data: 'papermill_category_name', name: 'papermill_category_name'},
              {data: 'district_name', name: 'district_name'},
              {data: 'regency_name', name: 'regency_name'},
              {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      table.on('draw.dt', function () {
            var info = table.page.info();
            table.column(0, { search: 'applied', order: 'applied', page: 'applied' }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

      $('#createNewPapermill').click(function () {
        window.location.href = "{{ route('papermills.createPapermill') }}";
      });


      $('body').on('click', '.editPapermill', function () {
        var papermill_id = $(this).data('id');
        window.location.href = "{{ route('papermills.index') }}" +'/' + papermill_id +'/edit';
      });

      $('body').on('click', '.deletePapermill', function () {

          var papermill_id = $(this).data("id");
          swal({
            title: "Are you sure?",
            text: "Apakah anda yakin untuk menghapus data ini ?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: "DELETE",
                        url: "{{ route('papermills.store') }}"+'/'+papermill_id,
                        success: function (data) {
                            toastr.options = {
                                "positionClass": "toast-bottom-right"
                            }
                            toastr.success('Papermill berhasil dihapus.');
                            table.draw();
                        },
                        error: function (data) {
                            console.log('Error:', data);
                        }
                    });
                } else {}
            });

      });

    });
</script>

@endpush